# Generated by Django 3.1 on 2020-08-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('customer', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('request', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=50)),
                ('time', models.IntegerField()),
            ],
        ),
    ]
