# Generated by Django 3.1 on 2020-08-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PHMapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
