# Generated by Django 3.1 on 2020-08-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHMapp', '0003_remove_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
